package main

const APP_NAME = "Linux Media Keys"
const ABOUT_TITLE = "Linux Media Keys"
const APP_VERSION = "0.1"
const RUN_COMMAND = "--run"
const VK_ESCAPE = "ESC"
const VK_DOWN = "Down"
const VK_UP = "Up"
const VK_RIGHT = "Right"
const VK_LEFT = "Left"
const VK_F4 = "F4"
const VK_F7 = "F7"
const VK_F8 = "F8"
const VK_F11 = "F11"
const VK_F12 = "F12"
